name: run-integration-tests
on:
  workflow_dispatch: {}
  workflow_call: {}
jobs:
  run-tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        parameter: [1, 2, 3]  # The matrix for different values    
    steps:
      - name: Run Integration Tests
        run: echo "Running integration tests with parameter ${{ matrix.parameter }}"
      - name: Save matrix parameter to a file
        run: echo "parameter=${{ matrix.parameter }}" > matrix_param.txt
      - name: Upload matrix parameter artifact
        uses: actions/upload-artifact@v4
        with:
          name: matrix-parameters
          path: matrix_param.txt
