name: send-slack-message
on:
  workflow_dispatch:
  # cron job to be implemented
jobs:
  # call the run-integration-tests
  call-run-integration-tests:
    # set the input to all matrix parameters
    uses: ./.github/workflows/run-integration-test.yml
  print-outputs:
    runs-on: ubuntu-latest
    needs: call-run-integration-tests
    steps:
      - name: Output aggregated test results
        run: |
          echo "${{ needs.call-run-integration-tests.outputs.test-case-exit-code-option-1}}"
          echo "${{ needs.call-run-integration-tests.outputs.test-case-exit-code-option-2 }}"
          echo "${{ needs.call-run-integration-tests.outputs.test-case-exit-code-option-3 }}"
          echo "${{ needs.call-run-integration-tests.outputs.test-case-artifact-url-option-1 }}"
          echo "${{ needs.call-run-integration-tests.outputs.test-case-artifact-url-option-2 }}"
          echo "${{ needs.call-run-integration-tests.outputs.test-case-artifact-url-option-3 }}"
  send-slack-message:
    runs-on: ubuntu-latest
    needs: call-run-integration-tests
    strategy:
      fail-fast: false
      matrix: 
        test_cases: ["option_1", "option_2", "option_3"]
    steps:
      - name: Send message for each option
        run: |
          echo "The exit code for ${{matrix.test_cases}} :"
          echo "${{ needs.call-run-integration-tests.outputs.test-case-exit-code-option-1}}"
          echo "::set-output name=needs.call-run-integration-tests.outputs.test-case-exit-code-${{ matrix.test_cases }}::$exit_code"
          echo "$exit_code"




      