name: send-slack-message
on:
  workflow_dispatch:
  # cron job to be implemented
jobs:
  # call the run-integration-tests
  call-run-integration-tests:
    # set the input to all matrix parameters
    uses: ./.github/workflows/run-integration-test.yml
  print-outputs:
    runs-on: ubuntu-latest
    needs: call-run-integration-tests
    steps:
      - name: Output aggregated test results
        env:
          TEST_CASES: ${{ needs.call-run-integration-tests.outputs.test_cases }}
        run: |
          echo "Test results JSON: ${{ needs.call-run-integration-tests.outputs.exit_codes }}"
          list_str="$TEST_CASES"
          cleaned_list_str=$(echo "$list_str" | sed 's/^\[\("\([^"]*\)"\)\(, \)*\]$/\1/g' | sed 's/","/,/g' | tr -d '"')

          # Debugging: Show the cleaned string
          echo "Cleaned string: $cleaned_list_str"

          # Step 2: Split the cleaned string into an array by commas
          IFS=',' read -r -a test_case_list <<< "$cleaned_list_str"

          echo "Array length: ${#test_case_list[@]}"
          echo "Converted array:"
          for test_case in "${test_case_list[@]}"; do
            echo "$test_case"
          done

          for test_case in "${test_case_list[@]}"; do
          echo "Downloading artifact for test case: $test_case"
      
          # Call the download-artifact action for each test case
          - name: Download artifact for $test_case
            uses: actions/download-artifact@v3
            with:
              name: "artifact-$test_case"  # Artifact name dynamically based on test case
              path: "myfile-$test_case"  # Path to save the artifact for the specific test case
          done


