name: send-slack-message
on:
  workflow_dispatch:
  # cron job to be implemented
jobs:
  # call the run-integration-tests
  call-run-integration-tests:
    # set the input to all matrix parameters
    uses: ./.github/workflows/run-integration-test.yml
  print-outputs:
    runs-on: ubuntu-latest
    needs: call-run-integration-tests
    steps:
      - name: Output aggregated test results
        env:
          TEST_CASES: ${{ needs.call-run-integration-tests.outputs.test_cases }}
        run: |
          echo "Test results JSON: ${{ needs.call-run-integration-tests.outputs.exit_codes }}"
          list_str="$TEST_CASES"
          test_case_list=$(echo "$list_str" | jq -r '.[]')

          # Check if list_str is empty
          if [ -z "$test_case_list" ]; then
            echo "Error: The test_case_list is empty!"
            exit 1
          fi

          # Debugging: Show the converted list
          echo "Converted list:"
          for test_case in $test_case_list; do
            echo "$test_case"
          done
