name: send-slack-message
on:
  workflow_dispatch:
  # cron job to be implemented
jobs:
  # call the run-integration-tests
  call-run-integration-tests:
    # set the input to all matrix parameters
    uses: ./.github/workflows/run-integration-test.yml
  print-outputs:
    runs-on: ubuntu-latest
    needs: call-run-integration-tests
    steps:
      - name: Output aggregated test results
        run: |
          echo "${{ needs.call-run-integration-tests.outputs.test-case-exit-code-option-1}}"
          echo "${{ needs.call-run-integration-tests.outputs.test-case-exit-code-option-2 }}"
          echo "${{ needs.call-run-integration-tests.outputs.test-case-exit-code-option-3 }}"
          echo "${{ needs.call-run-integration-tests.outputs.test-case-artifact-url-option-1 }}"
          echo "${{ needs.call-run-integration-tests.outputs.test-case-artifact-url-option-2 }}"
          echo "${{ needs.call-run-integration-tests.outputs.test-case-artifact-url-option-3 }}"
  send-slack-message:
    runs-on: ubuntu-latest
    needs: call-run-integration-tests
    strategy:
      fail-fast: false
      matrix: 
        test_cases: ['option-1', 'option-2', 'option-3']
    steps:
      - name: Send message for option 1
        if: ${{ matrix.test_cases == 'option-1' }}
        run: |
          echo "${{ needs.call-run-integration-tests.outputs.test-case-exit-code-option-1}}"
          echo "${{ needs.call-run-integration-tests.outputs.test-case-artifact-url-option-1 }}"
      - name: Send message for option 2
        if: ${{ matrix.test_cases == 'option-2' }}
        run: |
          echo "${{ needs.call-run-integration-tests.outputs.test-case-exit-code-option-2}}"
          echo "${{ needs.call-run-integration-tests.outputs.test-case-artifact-url-option-2 }}"
      - name: Send message for option 3
        if: ${{ matrix.test_cases == 'option-3' }}
        run: |
          echo "${{ needs.call-run-integration-tests.outputs.test-case-exit-code-option-3}}"
          echo "${{ needs.call-run-integration-tests.outputs.test-case-artifact-url-option-3 }}"
          




      