name: send-slack-message
on:
  workflow_run:
    workflows: ["run-integration-test"]
    types:
      - completed
jobs:
  download-get-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Download matrix parameters from artifact
        uses: actions/download-artifact@v4
        with:
          name: matrix-parameters-${{ matrix.parameter }}
