name: send-slack-message
on:
  workflow_dispatch:
  # cron job to be implemented
jobs:
  # call the run-integration-tests
  call-run-integration-tests:
    # set the input to all matrix parameters
    uses: ./.github/workflows/run-integration-test.yml
  print-outputs:
    runs-on: ubuntu-latest
    needs: call-run-integration-tests
    steps:
      - name: Output aggregated test results
        env:
          TEST_CASES: ${{ needs.call-run-integration-tests.outputs.test_cases }}
        run: |
          echo "Test results JSON: ${{ needs.call-run-integration-tests.outputs.exit_codes }}"
          list_str="$TEST_CASES"
          echo "Raw string: '$list_str'"
