name: send-slack-message
on:
  workflow_dispatch:
  # cron job to be implemented
jobs:
  # call the run-integration-tests
  call-run-integration-tests:
    # set the input to all matrix parameters
    uses: ./.github/workflows/run-integration-test.yml
  print-outputs:
    runs-on: ubuntu-latest
    needs: call-run-integration-tests
    steps:
      - name: Output aggregated test results
        env:
          TEST_CASES: ${{ needs.call-run-integration-tests.outputs.test_cases }}
        run: |
          echo "Test results JSON: ${{ needs.call-run-integration-tests.outputs.exit_codes }}"
          list_str="$TEST_CASES"
          # Clean up the string: Remove the surrounding quotes and escape characters
          cleaned_list_str=$(echo "$list_str" | sed 's/^"\(.*\)"$/\1/' | sed 's/\\"/"/g')
    
          # Debugging: Show the cleaned string
          echo "Cleaned string: '$cleaned_list_str'"

          # Now split the cleaned list by commas into an array
          IFS=',' read -r -a test_case_list <<< "$cleaned_list_str"

          # Check if list_str is empty
          if [ ${#test_case_list[@]} -eq 0 ]; then
            echo "Error: The test_case_list is empty!"
            exit 1
          fi

          echo "Array length: ${#test_case_list[@]}"
          echo "Converted list:"
          for test_case in "${test_case_list[@]}"; do
            echo "$test_case"
          done

          for test_case in "${test_case_list[@]}"; do
          echo "Downloading artifact for test case: $test_case"
      
          # Call the download-artifact action for each test case
          - name: Download artifact for $test_case
            uses: actions/download-artifact@v3
            with:
              name: "artifact-$test_case"  # Artifact name dynamically based on test case
              path: "myfile-$test_case"  # Path to save the artifact for the specific test case
          done


