name: send-slack-message
on:
  workflow_dispatch:
  # cron job to be implemented
jobs:
  # call the run-integration-tests
  call-run-integration-tests:
    # set the input to all matrix parameters
    uses: ./.github/workflows/run-integration-test.yml
  print-outputs:
    runs-on: ubuntu-latest
    needs: call-run-integration-tests
    steps:
      - name: Output aggregated test results
        run: |
          echo "${{ needs.call-run-integration-tests.outputs.test-case-exit-code-option-1}}"
          echo "${{ needs.call-run-integration-tests.outputs.test-case-exit-code-option-2 }}"
          echo "${{ needs.call-run-integration-tests.outputs.test-case-exit-code-option-3 }}"
          echo "${{ needs.call-run-integration-tests.outputs.test-case-artifact-url-option-1 }}"
          echo "${{ needs.call-run-integration-tests.outputs.test-case-artifact-url-option-2 }}"
          echo "${{ needs.call-run-integration-tests.outputs.test-case-artifact-url-option-3 }}"
  set-outputs:
    runs-on: ubuntu-latest
    needs: call-run-integration-tests
    strategy:
      fail-fast: false
      matrix: 
        test_cases: ['option-1', 'option-2', 'option-3']
    steps:
      - name: Set outputs
        id: variables
        run: |
          echo "Setting outputs"
          if [ "${{ matrix.test_cases }}" == "option-1" ]; then
            echo "EXIT_CODE='${{ needs.call-run-integration-tests.outputs.test-case-exit-code-option-1}}'" >> $GITHUB_OUTPUT
            echo "ARTIFACT_URL='${{ needs.call-run-integration-tests.outputs.test-case-artifact-url-option-1 }}'" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.test_cases }}" == "option-2" ]; then
            echo "EXIT_CODE='${{ needs.call-run-integration-tests.outputs.test-case-exit-code-option-2}}'" >> $GITHUB_OUTPUT
            echo "ARTIFACT_URL='${{ needs.call-run-integration-tests.outputs.test-case-artifact-url-option-2 }}'" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.test_cases }}" == "option-3" ]; then
            echo "EXIT_CODE='${{ needs.call-run-integration-tests.outputs.test-case-exit-code-option-3}}'" >> $GITHUB_OUTPUT
            echo "ARTIFACT_URL='${{ needs.call-run-integration-tests.outputs.test-case-artifact-url-option-3 }}'" >> $GITHUB_OUTPUT
          fi
      - name: Send slack message
        run: |
          echo ${{ steps.variables.EXIT_CODE }}




      
          




      