name: send-slack-message
on:
  workflow_dispatch:
  # cron job to be implemented
jobs:
  # call the run-integration-tests
  call-run-integration-tests:
    # set the input to all matrix parameters
    uses: ./.github/workflows/run-integration-test.yml
  print-outputs:
    runs-on: ubuntu-latest
    needs: call-run-integration-tests
    steps:
      - name: Output aggregated test results
        run: |
          echo "Test results JSON: ${{ needs.call-run-integration-tests.outputs.exit_codes }}"
          echo "${{ needs.call-run-integration-tests.outputs.test_cases }}"
          # Retrieve the string output
          list_str=""${{ needs.call-run-integration-tests.outputs.test_cases }}"

          # Convert the comma-separated string back into an array (list)
          IFS=',' read -r -a test_case_list <<< "$list_str"
          echo "Iterating over test cases:"

          # Iterate over the artifact names and download each one
          for artifact in "${test_case_list[@]}"; do
            echo "Downloading artifact: $artifact"
            # Download each artifact using the download-artifact action
            - name: Download $artifact
              uses: actions/download-artifact@v4
              with:
                name: artifact-$artifact
                path: "myfile-$artifact.txt"
          done