name: send-slack-message
on:
  workflow_run:
    workflows: ["run-integration-test"]
    types:
      - completed
jobs:
  download-get-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Download other matrix parameters artifacts
        run: |
          for param in 1 2 3; do
            echo "Downloading artifact for parameter $param"
            # Download the artifact dynamically based on the parameter number
            curl -L -o "matrix_param_${param}.txt" "https://github.com/${{ github.repository }}/actions/artifacts/${{ github.event.workflow_run.outputs['parameter-'${param}] }}"

          done
        
